### ISSUE TITLE
Improve blink

### ISSUE THREAD

**Issue by CommanderRedYT** [bobbycar-graz/bobbycar-boardcomputer-firmware#89]
- [x] Add more animations
- [x] Add feature to control whether blink only is in the back or back and front or the whole Bobbycar.
- [x] Fix blink directions (If ledstrip was glued on the wrong way, left and right blink are swapped)
- [x] Improve menu of blink animation to have selectable texts instead of number changer

**Comment by peterpoetzi** [comment]
Fix blink directions implemented in https://github.com/bobbycar-graz/bobbycar-boardcomputer-firmware/pull/90

**Comment by CommanderRedYT** [comment]
Features are coded, only need to push and merge
